version: "3.7"

services:
  user-service:
    build:
      context: .
      dockerfile: user_service/Dockerfile
    ports:
      - "8001:8001"
    environment:
      - AWS_REGION=eu-north-1
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
    depends_on:
      - localstack

  product-service:
    build:
      context: .
      dockerfile: product_service/Dockerfile
    ports:
      - "8002:8002"
    environment:
      - AWS_REGION=eu-north-1
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_ENDPOINT_URL=http://localstack:4566
    depends_on:
      - localstack

  cart-service:
    build:
      context: .
      dockerfile: cart_service/Dockerfile
    ports:
      - "8003:8003"
    environment:
      - AWS_REGION=eu-north-1
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
    depends_on:
      - localstack

  localstack:
    image: localstack/localstack
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
