version: "3.8"

services:
  user_service:
    build: ./user_service
    ports:
      - "8001:8001"
    environment:
      - AWS_REGION=eu-central-1
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - DYNAMODB_ENDPOINT_URL=http://host.docker.internal:8000
      - DYNAMODB_TABLE_NAME=users
      - SECRET_KEY=my_secret_key
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      - dynamodb

  cart_service:
    build: ./cart_service
    ports:
      - "8003:8003"
    environment:
      - DYNAMODB_ENDPOINT_URL=http://host.docker.internal:8000
      - DYNAMODB_TABLE_NAME=cart
    depends_on:
      - dynamodb

  product_service:
    build: ./product_service
    ports:
      - "8002:8002"
    environment:
      - AWS_REGION=eu-central-1
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - DYNAMODB_ENDPOINT_URL=http://host.docker.internal:8000
      - DYNAMODB_TABLE_NAME=products
    depends_on:
      - dynamodb

  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb
    ports:
      - "8000:8000"
    command: [ "-jar", "DynamoDBLocal.jar", "-sharedDb" ]
    volumes:
      - dynamodb_data:/home/dynamodblocal

volumes:
  dynamodb_data:
