name: Deploy to AWS ECS (Fargate) with DynamoDB and S3

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up AWS CLI with your credentials
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      # Set up Docker Buildx (needed for multi-architecture builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Log in to Amazon ECR
      - name: Log in to Amazon ECR
        run: |
          echo "Logging into Amazon ECR..."
          aws ecr get-login-password --region ${{ secrets.AWS_DEFAULT_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com
          
          # Check if the login was successful
          if [ $? -ne 0 ]; then
            echo "ECR login failed. Please verify your AWS credentials and region."
            exit 1
          fi

      # Build and push Docker images to ECR
      - name: Build and push Docker images to ECR
        run: |
          echo "Building and pushing Docker images..."
          # Create ECR repository if it doesn't exist
          aws ecr describe-repositories --repository-name user-service || aws ecr create-repository --repository-name user-service
          aws ecr describe-repositories --repository-name product-service || aws ecr create-repository --repository-name product-service
          aws ecr describe-repositories --repository-name cart-service || aws ecr create-repository --repository-name cart-service

          # Build and push Docker images for each service
          docker build -t user-service ./user_service 
          docker tag user-service:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com/user-service:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com/user-service:latest

          docker build -t product-service ./product_service
          docker tag product-service:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com/product-service:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com/product-service:latest

          docker build -t cart-service ./cart_service
          docker tag cart-service:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com/cart-service:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com/cart-service:latest

      # Create DynamoDB Tables (User, Product, and Cart)
      - name: Create DynamoDB Tables
        run: |
          echo "Creating DynamoDB tables..."
          aws dynamodb create-table \
            --table-name users \
            --attribute-definitions AttributeName=user_id,AttributeType=S \
            --key-schema AttributeName=user_id,KeyType=HASH \
            --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5 \
            --region ${{ secrets.AWS_DEFAULT_REGION }} || echo "Users table already exists"
          
          aws dynamodb create-table \
            --table-name products \
            --attribute-definitions AttributeName=product_id,AttributeType=S \
            --key-schema AttributeName=product_id,KeyType=HASH \
            --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5 \
            --region ${{ secrets.AWS_DEFAULT_REGION }} || echo "Products table already exists"
          
          aws dynamodb create-table \
            --table-name cart \
            --attribute-definitions AttributeName=user_id,AttributeType=S \
            --key-schema AttributeName=user_id,KeyType=HASH \
            --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5 \
            --region ${{ secrets.AWS_DEFAULT_REGION }} || echo "Carts table already exists"

      # Create S3 Bucket for Product Service (for file storage)
      - name: Create S3 Bucket for Product Service
        run: |
          echo "Creating S3 bucket for product service..."
          aws s3 mb s3://microcart-products --region ${{ secrets.AWS_DEFAULT_REGION }} || echo "S3 bucket already exists"

       # Create ECS Cluster if it doesn't exist
      - name: Create ECS Cluster if it doesn't exist
        run: |
          echo "Checking if ECS cluster exists..."
          CLUSTER_NAME="microcart-cluster"
          CLUSTER_STATUS=$(aws ecs describe-clusters --clusters $CLUSTER_NAME --query "clusters[0].status" --output text --region ${{ secrets.AWS_DEFAULT_REGION }})

          if [ "$CLUSTER_STATUS" == "ACTIVE" ]; then
            echo "Cluster '$CLUSTER_NAME' exists and is active."
          else
            echo "Cluster '$CLUSTER_NAME' does not exist or is not active. Creating it..."
            # Create ECS Cluster if it doesn't exist
            aws ecs create-cluster --cluster-name $CLUSTER_NAME --region ${{ secrets.AWS_DEFAULT_REGION }}
            echo "Cluster '$CLUSTER_NAME' created."
          fi
          
      # Register ECS Task Definitions
      - name: Register ECS Task Definitions
        run: |
          echo "Registering ECS Task Definition for user service.."
          cat > user-service-task.json <<EOF
          {
            "family": "user-service-task",
            "networkMode": "awsvpc",
            "containerDefinitions": [
              {
                "name": "user-service",
                "image": "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com/user-service:latest",
                "cpu": 256,
                "memory": 512,
                "essential": true,
                "portMappings": [
                  {
                    "containerPort": 80,
                    "hostPort": 80
                  }
                ]
              }
            ],
            "executionRoleArn": "arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/ecsTaskExecutionRole",
            "requiresCompatibilities": ["FARGATE"],
            "cpu": "256",
            "memory": "512"
          }
          EOF
          aws ecs register-task-definition --cli-input-json file://user-service-task.json

          echo "Registering ECS Task Definition for product service.."
          cat > product-service-task.json <<EOF
          {
            "family": "product-service-task",
            "networkMode": "awsvpc",
            "containerDefinitions": [
              {
                "name": "product-service",
                "image": "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com/product-service:latest",
                "cpu": 256,
                "memory": 512,
                "essential": true,
                "portMappings": [
                  {
                    "containerPort": 80,
                    "hostPort": 80
                  }
                ]
              }
            ],
            "executionRoleArn": "arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/ecsTaskExecutionRole",
            "requiresCompatibilities": ["FARGATE"],
            "cpu": "256",
            "memory": "512"
          }
          EOF
          aws ecs register-task-definition --cli-input-json file://product-service-task.json

          echo "Registering ECS Task Definition for cart service.."
          cat > cart-service-task.json <<EOF
          {
            "family": "cart-service-task",
            "networkMode": "awsvpc",
            "containerDefinitions": [
              {
                "name": "cart-service",
                "image": "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com/cart-service:latest",
                "cpu": 256,
                "memory": 512,
                "essential": true,
                "portMappings": [
                  {
                    "containerPort": 80,
                    "hostPort": 80
                  }
                ]
              }
            ],
            "executionRoleArn": "arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/ecsTaskExecutionRole",
            "requiresCompatibilities": ["FARGATE"],
            "cpu": "256",
            "memory": "512"
          }
          EOF
          aws ecs register-task-definition --cli-input-json file://cart-service-task.json

      # Create ECS Services if they do not exist or update them if they exist
      - name: Create or Update ECS Services
        run: |
          echo "Creating or updating ECS services for User, Product, and Cart..."
          
          # Function to create or update ECS service
          create_or_update_service() {
            SERVICE_NAME=$1
            TASK_DEFINITION=$2
            CLUSTER_NAME=$3
            SUBNETS=$4
            SECURITY_GROUPS=$5

            # Check if service exists
            SERVICE_EXISTS=$(aws ecs describe-services --cluster $CLUSTER_NAME --services $SERVICE_NAME --query 'services[0].serviceName' --output text)
            
            if [ "$SERVICE_EXISTS" == "$SERVICE_NAME" ]; then
              echo "$SERVICE_NAME exists. Updating the service..."
              aws ecs update-service \
                --cluster $CLUSTER_NAME \
                --service $SERVICE_NAME \
                --task-definition $TASK_DEFINITION \
                --desired-count 1 \
                --network-configuration "awsvpcConfiguration={subnets=[$SUBNETS],securityGroups=[$SECURITY_GROUPS],assignPublicIp=ENABLED}"
            else
              echo "$SERVICE_NAME does not exist. Creating the service..."
              aws ecs create-service \
                --cluster $CLUSTER_NAME \
                --service-name $SERVICE_NAME \
                --task-definition $TASK_DEFINITION \
                --desired-count 1 \
                --launch-type FARGATE \
                --network-configuration "awsvpcConfiguration={subnets=[$SUBNETS],securityGroups=[$SECURITY_GROUPS],assignPublicIp=ENABLED}"
            fi
          }

          # Create or update each service
          create_or_update_service "user-service" "user-service-task" "microcart-cluster" "${{ secrets.AWS_SUBNETS }}" "${{ secrets.AWS_SECURITY_GROUPS }}"
          create_or_update_service "product-service" "product-service-task" "microcart-cluster" "${{ secrets.AWS_SUBNETS }}" "${{ secrets.AWS_SECURITY_GROUPS }}"
          create_or_update_service "cart-service" "cart-service-task" "microcart-cluster" "${{ secrets.AWS_SUBNETS }}" "${{ secrets.AWS_SECURITY_GROUPS }}"
     
          # Output ECS Service URL
      - name: Output ECS service URLs
        run: |
          echo "User Service URL: http://$(aws ecs describe-services --cluster microcart-cluster --services user-service --query 'services[0].loadBalancers[0].dnsName' --output text)"
          echo "Product Service URL: http://$(aws ecs describe-services --cluster microcart-cluster --services product-service --query 'services[0].loadBalancers[0].dnsName' --output text)"
          echo "Cart Service URL: http://$(aws ecs describe-services --cluster microcart-cluster --services cart-service --query 'services[0].loadBalancers[0].dnsName' --output text)"
